baseurl = "http://gopherconbr.org/en"
languageCode = "en-us"
title = "GopherCon Brazil 2022"
contentdir = "content/en"
publishdir = "public/en"

[params]
    locale = "en-US"

[taxonomies]
  sponsor = "sponsors"
  speaker = "speakers"
  event = "events"
  day = "days"
